### ISSUE TITLE
When clicking a link, you're asked to sign in again when you return

### ISSUE THREAD

**Issue by sirwlm** [WiseClock/flarum-ext-reply2see#3]
So this is odd, but when you reply to a thread, and then you click a link, it takes you to the link but the current tab also loads the login modal, you're not actually logged out, but it is annoying to have to click the X every time: https://i.imgur.com/4WWPVUQ.gif

Otherwise great extension! 

Using Dev tools, it looks like 'setTimeout' is being called when the link is clicked, google turned up nothing for that besides a flarum bug with the scroll bar.

**Comment by n0099** [comment]
possible related: https://github.com/oaklinq/flarum-ext-reply2see/pull/1
